### ISSUE TITLE
Following the below instructions does not work

### ISSUE THREAD

**Issue by andyfensham** [NetCoreApps/BookingsCrud#1]
When you following the following instructions I get the following errors.

``
$ app download NetCoreApps/BookingsCrud
$ cd BookingsCrud\Acme
$ dotnet run
``
![Snag_138a1f75](https://user-images.githubusercontent.com/5065306/122029811-7f243080-cdcd-11eb-9ee7-426ea66fb9f4.png)

**Comment by mythz** [comment]
Since these are referencing the pre-release packages it has the same issue as https://github.com/NetCoreApps/NorthwindCrud/issues/3#event-4886682840

Where you'd need to clear your NuGet packages cache before doing a full app restore to get the latest pre-release package versions:

    $ nuget locals all -clear

After which downloading & running the project should work as expected:

    $ mkdir BookingsCrud && cd BookingsCrud
    $ app download NetCoreApps/BookingsCrud 
    $ cd Acme 
    $ dotnet run

![image](https://user-images.githubusercontent.com/89361/122059491-4614ac00-ce1f-11eb-9553-5b449fad2865.png)

Note: the latest version of `app` tool (i.e. `dotnet tool update -g app`) writes the project files to the current directory, you can specify to save it to a different folder with `-out`, e.g:

    $ app download NetCoreApps/BookingsCrud -out BookingsCrud
